language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t txfs19260817/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true txfs19260817/react-test npm run test -- --coverage

after_success:
  - docker build -t txfs19260817/multi-client ./client
  - docker build -t txfs19260817/multi-nginx ./nginx
  - docker build -t txfs19260817/multi-server ./server
  - docker build -t txfs19260817/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to Docker hub
  - docker push txfs19260817/multi-client
  - docker push txfs19260817/multi-nginx
  - docker push txfs19260817/multi-server
  - docker push txfs19260817/multi-worker